# Generated by Django 4.2.5 on 2024-10-04 01:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product_stock_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_information",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Enter additional information here", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="nutritional_value",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Enter nutritional value here", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Enter description here", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2, default="100000", max_digits=99999999999
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="100000", max_digits=99999999999
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
